---
name: FastForward
loglevel: warn

listeners:
  - name: TCP Listener
    type: tcp
    port: 9001
    enabled: yes
  - name: UDP Listener
    type: udp
    port: 9002
    enabled: yes
  - name: HTTP Listener
    type: http
    port: 8088
    enabled: true
  - name: Unix Socket Listener
    type: uds
    socket: /tmp/listen.sock
    enabled: no

sinks:
  - name: Https forwarder
    type: http
    url: http://localhost:8080
    api_key: some_random_api_key
    enabled: yes
    batch_send: false
    cache_file_name: http_sink.cache
    cache_size: 1G
  - name: Console print
    type: stdout
    enabled: no
    batch_send: no
  - name: Save into file
    type: file
    path: /tmp/events.log
    enabled: no
    batch_send: true

acl:
  allow:
    - 127.0.0.1
    - 10.0.0.0/8
  deny:
